<?php
namespace Kily\Delivery\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-30 at 23:57:20.
 */
class GarantpostTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Garantpost
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Garantpost;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Service\Garantpost::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Service\Garantpost::subservices
     * @todo   Implement testSubservices().
     */
    public function testSubservices()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
