<?php
namespace Kily\Delivery\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-28 at 14:47:10.
 */
class PonyexpressTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Service\RuPonyexpress::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        $service = new Ponyexpress();
        $this->assertEquals('ponyexpress', $service->getName());
    }
}
