<?php
namespace Kily\Delivery\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-27 at 15:13:22.
 */
class RuEmspostTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RuEmspost
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Service\RuEmspost::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        $service = new RuEmspost();
        $this->assertEquals('ru_emspost', $service->getName());
    }
}
