<?php
namespace Kily\Delivery\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-27 at 15:13:22.
 */
class ServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Service
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Service\Service::getName
     * @expectedException \Kily\Delivery\Exception\ShouldBeOverriden
     */
    public function testGetName()
    {
        $service = new Service;
        $service->getName();
    }
}
