<?php
namespace Kily\Delivery\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-27 at 15:13:22.
 */
class ServiceFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ServiceFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Service\ServiceFactory::factory
     */
    public function testFactory()
    {
        $service = ServiceFactory::factory("ru_emspost");
        $this->assertEquals('Kily\Delivery\Service\RuEmspost', get_class($service));
        $service = ServiceFactory::factory("ponyexpress");
        $this->assertEquals('Kily\Delivery\Service\Ponyexpress', get_class($service));
    }
}
