<?php
namespace Kily\Delivery\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-02 at 12:42:27.
 */
class AddressTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Address
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Address;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert ("1.1;2.2") == $this->object.
     *
     * @covers Kily\Delivery\Model\Address::setCoordinates
     */
    public function testSetCoordinates()
    {
        $this->assertEquals(
            $this->object,
            $this->object->setCoordinates("1.1;2.2")
        );
    }

    /**
     * Generated from @assert ([1.1,2.2]) == $this->object.
     *
     * @covers Kily\Delivery\Model\Address::setCoordinates
     */
    public function testSetCoordinates2()
    {
        $this->assertEquals(
            $this->object,
            $this->object->setCoordinates([1.1,2.2])
        );
    }

    /**
     * Generated from @assert (new Coordinates("1.1","2.2")) == $this->object.
     *
     * @covers Kily\Delivery\Model\Address::setCoordinates
     */
    public function testSetCoordinates3()
    {
        $this->assertEquals(
            $this->object,
            $this->object->setCoordinates(new Coordinates("1.1","2.2"))
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getCoordinates
     * @todo   Implement testGetCoordinates().
     */
    public function testGetCoordinates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getLatitude
     * @todo   Implement testGetLatitude().
     */
    public function testGetLatitude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setLatitude
     * @todo   Implement testSetLatitude().
     */
    public function testSetLatitude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getLongitude
     * @todo   Implement testGetLongitude().
     */
    public function testGetLongitude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setLongitude
     * @todo   Implement testSetLongitude().
     */
    public function testSetLongitude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getBounds
     * @todo   Implement testGetBounds().
     */
    public function testGetBounds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setBounds
     * @todo   Implement testSetBounds().
     */
    public function testSetBounds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getStreetNumber
     * @todo   Implement testGetStreetNumber().
     */
    public function testGetStreetNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setStreetNumber
     * @todo   Implement testSetStreetNumber().
     */
    public function testSetStreetNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getStreetName
     * @todo   Implement testGetStreetName().
     */
    public function testGetStreetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setStreetName
     * @todo   Implement testSetStreetName().
     */
    public function testSetStreetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getLocality
     * @todo   Implement testGetLocality().
     */
    public function testGetLocality()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setLocality
     * @todo   Implement testSetLocality().
     */
    public function testSetLocality()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getPostalCode
     * @todo   Implement testGetPostalCode().
     */
    public function testGetPostalCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setPostalCode
     * @todo   Implement testSetPostalCode().
     */
    public function testSetPostalCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getSubLocality
     * @todo   Implement testGetSubLocality().
     */
    public function testGetSubLocality()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setSubLocality
     * @todo   Implement testSetSubLocality().
     */
    public function testSetSubLocality()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getAdminLevels
     * @todo   Implement testGetAdminLevels().
     */
    public function testGetAdminLevels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setAdminLevels
     * @todo   Implement testSetAdminLevels().
     */
    public function testSetAdminLevels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getCountry
     * @todo   Implement testGetCountry().
     */
    public function testGetCountry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setCountry
     * @todo   Implement testSetCountry().
     */
    public function testSetCountry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getCountryCode
     * @todo   Implement testGetCountryCode().
     */
    public function testGetCountryCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setCountryCode
     * @todo   Implement testSetCountryCode().
     */
    public function testSetCountryCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getTimezone
     * @todo   Implement testGetTimezone().
     */
    public function testGetTimezone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::setTimezone
     * @todo   Implement testSetTimezone().
     */
    public function testSetTimezone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Address::getFullAddress
     * @todo   Implement testGetFullAddress().
     */
    public function testGetFullAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
