<?php
namespace Kily\Delivery\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-30 at 23:57:19.
 */
class BoundsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Bounds
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Bounds;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::getSouth
     * @todo   Implement testGetSouth().
     */
    public function testGetSouth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::setSouth
     * @todo   Implement testSetSouth().
     */
    public function testSetSouth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::getWest
     * @todo   Implement testGetWest().
     */
    public function testGetWest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::setWest
     * @todo   Implement testSetWest().
     */
    public function testSetWest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::getNorth
     * @todo   Implement testGetNorth().
     */
    public function testGetNorth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::setNorth
     * @todo   Implement testSetNorth().
     */
    public function testSetNorth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::getEast
     * @todo   Implement testGetEast().
     */
    public function testGetEast()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::setEast
     * @todo   Implement testSetEast().
     */
    public function testSetEast()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::isDefined
     * @todo   Implement testIsDefined().
     */
    public function testIsDefined()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Bounds::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
