<?php
namespace Kily\Delivery\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-30 at 23:57:19.
 */
class CoordinatesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Coordinates
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Coordinates;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Model\Coordinates::getLatitude
     * @todo   Implement testGetLatitude().
     */
    public function testGetLatitude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Coordinates::setLatitude
     * @todo   Implement testSetLatitude().
     */
    public function testSetLatitude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Coordinates::getLongitude
     * @todo   Implement testGetLongitude().
     */
    public function testGetLongitude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Model\Coordinates::setLongitude
     * @todo   Implement testSetLongitude().
     */
    public function testSetLongitude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
