<?php
namespace Kily\Delivery\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-30 at 23:57:19.
 */
class GeocodedAddressTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GeocodedAddress
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GeocodedAddress;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Model\GeocodedAddress::getFullAddress
     * @todo   Implement testGetFullAddress().
     */
    public function testGetFullAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
