<?php
namespace Kily\Delivery\Provider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-30 at 23:57:21.
 */
class HttpProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HttpProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HttpProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
