<?php
namespace Kily\Delivery\Provider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-02 at 12:34:40.
 */
class ProviderFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ProviderFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ProviderFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Provider\ProviderFactory::factory
     * @todo   Implement testFactory().
     */
    public function testFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kily\Delivery\Provider\ProviderFactory::listProviders
     * @todo   Implement testListProviders().
     */
    public function testListProviders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
