<?php
namespace Kily\Delivery;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-28 at 14:47:27.
 */
class CalculatorResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\CalculatorResponse::getAttributes
     */
    public function testGetAttributes()
    {
        $object = new CalculatorResponse;
        $object->cost = 1000;
        $this->assertEquals([
            'service'=>null,
            'cost'=>1000,
            'period'=>null,
        ],$object->attributes);

    }
}
