<?php
namespace Kily\Delivery;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-27 at 15:12:20.
 */
class UtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Utils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kily\Delivery\Utils::camelize
     */
    public function testCamelize()
    {
        $this->assertEquals('test',Utils::camelize('test'));
        $this->assertEquals('ruTestOlolo',Utils::camelize('ru_test_ololo'));
    }

    /**
     * @covers Kily\Delivery\Utils::addrFromString
     */
    public function testAddrFromString()
    {
        $this->assertEquals(Utils::addrFromString("Москва")->getLocality(),'Москва');
        $this->assertEquals(Utils::addrFromString("Кишенев")->getLocality(),'Кишинёв');
    }
}
